all:
	../raytracer ./test_scenes/inputs/simple.xml
	../raytracer ./test_scenes/inputs/simple_shading.xml
	../raytracer ./test_scenes/inputs/simple_reflectance.xml
	../raytracer ./test_scenes/inputs/marbles.xml
	../raytracer ./test_scenes/inputs/mirror_spheres.xml
	../raytracer ./test_scenes/inputs/cornellbox.xml
	../raytracer ./test_scenes/inputs/monkey.xml
	../raytracer ./test_scenes/inputs/bunny.xml
	../raytracer ./test_scenes/inputs/car.xml
	../raytracer ./test_scenes/inputs/low_poly.xml
	../raytracer ./test_scenes/inputs/killeroo.xml
	../raytracer ./test_scenes/inputs/dragon_lowres.xml
	../raytracer ./test_scenes/inputs/berserker.xml
	../raytracer ./test_scenes/inputs/horse_and_mug.xml